package com.xcj.transaction;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;

public class DeptbakDAOImpl extends SqlMapClientDaoSupport implements DeptbakDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPTBAK
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public DeptbakDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPTBAK
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public void insert(Deptbak record) {
		getSqlMapClientTemplate().insert(
				"SCOTT_DEPTBAK.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPTBAK
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public int updateByPrimaryKey(Deptbak record) {
		int rows = getSqlMapClientTemplate().update(
				"SCOTT_DEPTBAK.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPTBAK
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public int updateByPrimaryKeySelective(Deptbak record) {
		int rows = getSqlMapClientTemplate().update(
				"SCOTT_DEPTBAK.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPTBAK
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public List selectByExample(DeptbakExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"SCOTT_DEPTBAK.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPTBAK
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public Deptbak selectByPrimaryKey(Short deptno) {
		Deptbak key = new Deptbak();
		key.setDeptno(deptno);
		Deptbak record = (Deptbak) getSqlMapClientTemplate().queryForObject(
				"SCOTT_DEPTBAK.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPTBAK
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public int deleteByExample(DeptbakExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"SCOTT_DEPTBAK.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPTBAK
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public int deleteByPrimaryKey(Short deptno) {
		Deptbak key = new Deptbak();
		key.setDeptno(deptno);
		int rows = getSqlMapClientTemplate().delete(
				"SCOTT_DEPTBAK.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPTBAK
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public int countByExample(DeptbakExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"SCOTT_DEPTBAK.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPTBAK
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public int updateByExampleSelective(Deptbak record, DeptbakExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("SCOTT_DEPTBAK.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPTBAK
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public int updateByExample(Deptbak record, DeptbakExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"SCOTT_DEPTBAK.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table SCOTT.DEPTBAK
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	private static class UpdateByExampleParms extends DeptbakExample {
		private Object record;

		public UpdateByExampleParms(Object record, DeptbakExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}