package com.xcj.transaction;

public class Deptpk {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SCOTT.DEPTPK.DEPTNO
     *
     * @abatorgenerated Tue Mar 12 17:25:30 CST 2013
     */
    private Short deptno;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SCOTT.DEPTPK.DEPTNO
     *
     * @return the value of SCOTT.DEPTPK.DEPTNO
     *
     * @abatorgenerated Tue Mar 12 17:25:30 CST 2013
     */
    public Short getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SCOTT.DEPTPK.DEPTNO
     *
     * @param deptno the value for SCOTT.DEPTPK.DEPTNO
     *
     * @abatorgenerated Tue Mar 12 17:25:30 CST 2013
     */
    public void setDeptno(Short deptno) {
        this.deptno = deptno;
    }
}