package com.xcj.transaction;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;

public class DeptDAOImpl implements DeptDAO {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public DeptDAOImpl(SqlMapClient sqlMapClient)
    {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public void insert(Dept record)
        throws SQLException
    {
        sqlMapClient.insert("SCOTT_DEPT.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public int updateByPrimaryKey(Dept record)
        throws SQLException
    {
        int rows = sqlMapClient.update("SCOTT_DEPT.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public int updateByPrimaryKeySelective(Dept record)
        throws SQLException
    {
        int rows = sqlMapClient.update("SCOTT_DEPT.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public List selectByExample(DeptExample example)
        throws SQLException
    {
        List list = sqlMapClient.queryForList("SCOTT_DEPT.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public Dept selectByPrimaryKey(Short deptno)
        throws SQLException
    {
        Dept key = new Dept();
        key.setDeptno(deptno);
        Dept record = (Dept)sqlMapClient.queryForObject("SCOTT_DEPT.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public int deleteByExample(DeptExample example)
        throws SQLException
    {
        int rows = sqlMapClient.delete("SCOTT_DEPT.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public int deleteByPrimaryKey(Short deptno)
        throws SQLException
    {
        Dept key = new Dept();
        key.setDeptno(deptno);
        int rows = sqlMapClient.delete("SCOTT_DEPT.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public int countByExample(DeptExample example)
        throws SQLException
    {
        Integer count = (Integer)sqlMapClient.queryForObject("SCOTT_DEPT.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public int updateByExampleSelective(Dept record, DeptExample example)
        throws SQLException
    {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("SCOTT_DEPT.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public int updateByExample(Dept record, DeptExample example)
        throws SQLException
    {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("SCOTT_DEPT.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS. This class corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    private static class UpdateByExampleParms extends DeptExample
    {
        private Object record;

        public UpdateByExampleParms(Object record, DeptExample example)
        {
            super(example);
            this.record = record;
        }

        public Object getRecord()
        {
            return record;
        }
    }
}