package com.xcj.transaction;

import java.sql.SQLException;
import java.util.List;

public interface DeptpkDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCOTT.DEPTPK
     *
     * @abatorgenerated Tue Mar 12 17:25:30 CST 2013
     */
    void insert(Deptpk record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCOTT.DEPTPK
     *
     * @abatorgenerated Tue Mar 12 17:25:30 CST 2013
     */
    List selectByExample(DeptpkExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCOTT.DEPTPK
     *
     * @abatorgenerated Tue Mar 12 17:25:30 CST 2013
     */
    int deleteByExample(DeptpkExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCOTT.DEPTPK
     *
     * @abatorgenerated Tue Mar 12 17:25:30 CST 2013
     */
    int countByExample(DeptpkExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCOTT.DEPTPK
     *
     * @abatorgenerated Tue Mar 12 17:25:30 CST 2013
     */
    int updateByExampleSelective(Deptpk record, DeptpkExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SCOTT.DEPTPK
     *
     * @abatorgenerated Tue Mar 12 17:25:30 CST 2013
     */
    int updateByExample(Deptpk record, DeptpkExample example) throws SQLException;
}