package com.xcj.transaction;

public class Dept {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column SCOTT.DEPT.DEPTNO
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    private Short deptno;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column SCOTT.DEPT.DNAME
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    private String dname;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column SCOTT.DEPT.LOC
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    private String loc;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column SCOTT.DEPT.DEPTNO
     * @return  the value of SCOTT.DEPT.DEPTNO
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public Short getDeptno()
    {
        return deptno;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column SCOTT.DEPT.DEPTNO
     * @param deptno  the value for SCOTT.DEPT.DEPTNO
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public void setDeptno(Short deptno)
    {
        this.deptno = deptno;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column SCOTT.DEPT.DNAME
     * @return  the value of SCOTT.DEPT.DNAME
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public String getDname()
    {
        return dname;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column SCOTT.DEPT.DNAME
     * @param dname  the value for SCOTT.DEPT.DNAME
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public void setDname(String dname)
    {
        this.dname = dname;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column SCOTT.DEPT.LOC
     * @return  the value of SCOTT.DEPT.LOC
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public String getLoc()
    {
        return loc;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column SCOTT.DEPT.LOC
     * @param loc  the value for SCOTT.DEPT.LOC
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    public void setLoc(String loc)
    {
        this.loc = loc;
    }
}