package com.xcj.transaction;

import java.sql.SQLException;
import java.util.List;

public interface DeptDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    void insert(Dept record)
        throws SQLException;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    int updateByPrimaryKey(Dept record)
        throws SQLException;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    int updateByPrimaryKeySelective(Dept record)
        throws SQLException;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    List selectByExample(DeptExample example)
        throws SQLException;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    Dept selectByPrimaryKey(Short deptno)
        throws SQLException;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    int deleteByExample(DeptExample example)
        throws SQLException;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    int deleteByPrimaryKey(Short deptno)
        throws SQLException;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    int countByExample(DeptExample example)
        throws SQLException;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    int updateByExampleSelective(Dept record, DeptExample example)
        throws SQLException;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
     * @abatorgenerated  Tue Mar 12 17:25:30 CST 2013
     */
    int updateByExample(Dept record, DeptExample example)
        throws SQLException;
}