package com.xcj.transaction;

public class Deptbak {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SCOTT.DEPTBAK.DEPTNO
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	private Short deptno;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SCOTT.DEPTBAK.DNAME
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	private String dname;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SCOTT.DEPTBAK.DEPTNO
	 * @return  the value of SCOTT.DEPTBAK.DEPTNO
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public Short getDeptno() {
		return deptno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SCOTT.DEPTBAK.DEPTNO
	 * @param deptno  the value for SCOTT.DEPTBAK.DEPTNO
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public void setDeptno(Short deptno) {
		this.deptno = deptno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SCOTT.DEPTBAK.DNAME
	 * @return  the value of SCOTT.DEPTBAK.DNAME
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public String getDname() {
		return dname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SCOTT.DEPTBAK.DNAME
	 * @param dname  the value for SCOTT.DEPTBAK.DNAME
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public void setDname(String dname) {
		this.dname = dname;
	}
}