package com.xcj.transaction;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DeptDAOImpl extends SqlMapClientDaoSupport implements DeptDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public DeptDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public void insert(Dept record) {
		getSqlMapClientTemplate().insert("SCOTT_DEPT.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public int updateByPrimaryKey(Dept record) {
		int rows = getSqlMapClientTemplate().update(
				"SCOTT_DEPT.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public int updateByPrimaryKeySelective(Dept record) {
		int rows = getSqlMapClientTemplate().update(
				"SCOTT_DEPT.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public List selectByExample(DeptExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"SCOTT_DEPT.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public Dept selectByPrimaryKey(Short deptno) {
		Dept key = new Dept();
		key.setDeptno(deptno);
		Dept record = (Dept) getSqlMapClientTemplate().queryForObject(
				"SCOTT_DEPT.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public int deleteByExample(DeptExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"SCOTT_DEPT.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public int deleteByPrimaryKey(Short deptno) {
		Dept key = new Dept();
		key.setDeptno(deptno);
		int rows = getSqlMapClientTemplate().delete(
				"SCOTT_DEPT.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public int countByExample(DeptExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"SCOTT_DEPT.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public int updateByExampleSelective(Dept record, DeptExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"SCOTT_DEPT.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SCOTT.DEPT
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	public int updateByExample(Dept record, DeptExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"SCOTT_DEPT.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table SCOTT.DEPT
	 * @abatorgenerated  Sun Mar 17 19:21:29 CST 2013
	 */
	private static class UpdateByExampleParms extends DeptExample {
		private Object record;

		public UpdateByExampleParms(Object record, DeptExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}